{{- $oc4 := and .Values.openshift (semverCompare ">=1.12-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) -}}
{{- $oc3 := and .Values.openshift (not $oc4) (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) -}}
{{- if $oc3 }}
apiVersion: authorization.openshift.io/v1
{{- else if (semverCompare ">=1.8-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: v1
{{- end }}
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.name }}
rules:
  - 
    apiGroups: 
      - ""
    resources: 
      - configmaps
      - endpoints
      - events
      - limitranges
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - replicationcontrollers
      - resourcequotas
      - services
    verbs: 
      - list
      - watch
  - 
    apiGroups: 
      - batch
    resources: 
      - cronjobs
      - jobs
    verbs: 
      - list
      - watch
  - 
    apiGroups: 
      - extensions
      - apps
    resources: 
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: 
      - list
      - watch
  - 
    apiGroups: 
      - autoscaling
    resources: 
      - horizontalpodautoscalers
    verbs: 
      - list
      - watch
  - 
    apiGroups: 
      - extensions
      - networking.k8s.io
    resources: 
      - ingress
    verbs: 
      - list
      - watch
  - 
    apiGroups: 
      - policy
    resources: 
      - poddisruptionbudgets
    verbs: 
      - list
      - watch
  - 
    apiGroups: 
      - storage.k8s.io
    resources: 
      - storageclasses
    verbs: 
      - list
      - watch
  - 
    apiGroups: 
      - autoscaling.k8s.io
    resources: 
      - verticalpodautoscalers
    verbs: 
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - watch
# List CRDs that you want to watch here
# Istio is just here as an example.  Alternatively if you want to get all CRDs its possible to add '*'
# to apiGroups, but that would give sloop permissions to read secrets which may not be desirable
  - apiGroups:
      - authentication.istio.io
      - config.istio.io
      - networking.istio.io
      - rbac.istio.io
      - security.istio.io
    resources:
      - '*'
    verbs:
      - list
      - watch
