apiVersion: v1
kind: Service
metadata:
  name: {{ template "phpipam.fullname" . }}
  labels:
    app: {{ template "phpipam.name" . }}
    chart: {{ template "phpipam.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "phpipam.name" . }}
    release: {{ .Release.Name }}
